# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: 
date_format: "ordinal"
title: MF
subtitle: "A blog site that records everything"
description: "A blog site that records everything"
keywords: blog
timezone: 
encoding: "utf-8"
repository: mfuu/mfuu.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 可选组件配置
components:
    # 分享
    # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
    share:
        enabled: true
        hide-platforms: douban,linkedin
    # 不蒜子访问统计
    busuanzi:
        enabled: true
        start_date: 2019-06-10
    # My Popular Repositories
    side_bar_repo:
        enabled: true
        limit: 5
    # 文章字数统计
    word_count:
        enabled: true
    # 页面右上角，以及「关于」页面的二维码
    # 修改图片请替换 assets/images/qrcode.jpg
    qrcode:
        enabled: false
        image_alt: ""
    # 维基索引页使用哪种视图，支持 列表（list）/分类（cate）
    wiki:
        view: cate
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 代码高亮风格，支持theme列表可见 assets/css/markdown
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: mfuu
organization: 
organization_url: 
github_username: mfuu
location: Chongqing, China
email: mfuu1998@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /archives/
    label: 归档

#   -
#     href: /open-source/
#     label: 开源

#   -
#     href: /wiki/
#     label: 维基

#   -
#     href: /links/
#     label: 链接

  -
    href: /about/
    label: 关于


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: gitalk, utterances
comments_provider: gitalk
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: mfuu
    repo: mfuu.github.io
    clientID: 425281566fa2c21accf0
    clientSecret: cc605a5d6af0c0564bbfe768ed4bebb2f4dd2a63
# https://utteranc.es/
utterances:
    repo: mfuu/mfuu.github.io
    theme: github-light
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: 
    adsense:
        footer: false
        sidebar: false 
        sidebar-detail: false 
        content_header: false
        content_footer: false

